name = "skyroute-enterprise"
account_id = "4b373ad750503e164fba7edf76322413"
main = "index.js"
compatibility_date = "2025-04-08"

[build]
command = ""

[vars]
CF_API_TOKEN = "6y1UyXmJN98BFSvnzmxGKkp-7UsC8kJcCc9lXhwo"
CF_ACCOUNT_ID = "4b373ad750503e164fba7edf76322413"
PROXY_AUTH_TOKEN = "k4f8ad9fg4k8j3fa87f9"

routes = [
  "home.mingleedan.org/*",
  "admin.mingleedan.org/*",
  "api.mingleedan.org/*",
  "webhook.mingleedan.org/*",
  "skyroute-enterprise.mingleedan.org/*"
]

triggers = { crons = ["*/30 * * * *"] }

[observability.logs]
enabled = true
